// AUTHENTICATION
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
// CHECKOUT
export const CHECKOUT_QR_SCANNED = 'CHECKOUT_QR_SCANNED';
export const CHECKOUT_SET_LICENCE_PLATE = 'CHECKOUT_SET_LICENCE_PLATE';
// ALERT 
export const ALERT_SET_MESSAGE = 'ALERT_SET_MESSAGE'